spring.application.name=meneses_backend
spring.datasource.url=jdbc:mysql://localhost:3306/bd_meneses
spring.datasource.username=conexion
spring.datasource.password=qwerty$1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=8080
